[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Teaching"
  pageRef = "teaching"
  weight = 40

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 50

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 60

[[footer]]
  name = "Google Scholar"
  url = "https://scholar.google.com/citations?hl=en&user=EK_dBqoAAAAJ"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/zehsilva"
  weight = 20

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/eliezersilva/"
  weight = 30

[[footer]]
  name = "ORCID"
  url = "https://orcid.org/0000-0002-5462-9782"
  weight = 40

[[footer]]
  name = "CV"
  url = "/about/pdf/cv_eliezer.pdf"
  weight = 50

[[footer]]
  name = "Lattes"
  url = "http://lattes.cnpq.br/9396110273991411"
  weight = 60
