
[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 40

[[footer]]
  name = "GScholar"
  url = "https://scholar.google.com/citations?hl=en&user=EK_dBqoAAAAJ"
  weight = 10

[[footer]]
  name = "zehsilva@github"
  url = "https://github.com/zehsilva"
  weight = 10

[[footer]]
  name = "sereliezer@x"
  url = "https://twitter.com/sereliezer"
  weight = 20
  
[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/eliezersilva/"
  weight = 20

[[footer]]
  name = "CV (pdf)"
  url = "about/pdf/cv_eliezer.pdf"
  weight = 30

[[footer]]
  name = "CV Lattes (pt-br)"
  url = "http://lattes.cnpq.br/9396110273991411"
  weight = 40

[[footer]]
  name = "Mini CV"
  url = "https://zehsilva.github.io"
  weight = 45

[[footer]]
  name = "ORCID"
  url = "https://orcid.org/0000-0002-5462-9782"
  weight = 50
  