colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true
footer.showAppearanceSwitcher = true
header.layout = "hybrid"
mainSections = ["blog","publications"]

[homepage]
layout = "profile"
showRecent = true
recentLimit = 5


[list]
showSummary = true
showTaxonomies = true

[article]
showTableOfContents = true
showTaxonomies = true
showReadingTime = false
showWordCount = true
showPagination = true
showAuthor = true
